<?php
namespace App\Lib;

class TweetController extends \Noweh\TwitterApi\AbstractController
{
    private string $nextToken = "";

    public function setNextToken(string $nextToken)
    {
        $this->nextToken = $nextToken;
    }

    public function setEndpoint(string $endpoint): void
    {
        if ($this->nextToken) {
            $endpoint .= '?pagination_token='.$this->nextToken;
        }
        parent::setEndpoint($endpoint); // TODO: Change the autogenerated stub
    }

}