<?php
namespace App\Lib;

class TweetController extends \Noweh\TwitterApi\AbstractController
{
    private string $nextToken = "";

    public function setNextToken(string $nextToken)
    {
        $this->nextToken = $nextToken;
    }

    public function setEndpoint(string $endpoint, $extraInfo = false): void
    {
        if ($this->nextToken) {
            $endpoint .= '?pagination_token='.$this->nextToken;
        }

        if ($extraInfo) {
            $endpoint .= '?expansions=author_id,attachments.media_keys&user.fields=id,name,username&media.fields=url,type,width,height,preview_image_url,variants';
        }
        parent::setEndpoint($endpoint); // TODO: Change the autogenerated stub
    }

}